name: terraform plan

run-name: terraform plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "stg"
        type: choice
        options:
          - prd
          - stg
          - dev
      resource:
        description: "Target Resource"
        required: true
        type: choice
        options:
          - database
          - ecs
          - network

jobs:
  apply:
    runs-on: ubuntu-22.04
    name: terraform plan
    steps:
      - run: echo "test"

      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
